#!/usr/bin/python3
from models.base_model import BaseModel

class Amenity(BaseModel):
    """Amenity class inherits from BaseModel and represents an amenity."""

    def __init__(self, *args, **kwargs):
        """Initializes an Amenity instance."""
        super().__init__(*args, **kwargs)
        self.name = kwargs.get('name', '')

    def __str__(self):
        """Returns string representation of the Amenity instance."""
        return "[Amenity] ({}) {}".format(self.id, self.name)
